export { default as Airdrop } from './Airdrop.png';
export { default as Exclude } from './Exclude.png';
export { default as ExcludeMobile } from './ExcludeMobile.png';
export { default as Staking } from './Staking.png';
export { default as Swap } from './Swap.png';
// src/assets/images/icons/git.svg src/assets/images/icons/Linkdin.svg src/assets/images/icons/mail.svg src/assets/images/icons/telegram.svg src/assets/images/icons/twitter.svg
export { default as Git } from './Git.svg';
export { default as Linkdin } from './Linkdin.svg';
export { default as Mail } from './Mail.svg';
export { default as Telegram } from './Telegram.svg';
export { default as Twitter } from './Twitter.svg';
export { default as GSR } from './ourPartner/gsr.svg';
export { default as Ton } from './ourPartner/ton.svg';
export { default as Alphanonce } from './ourPartner/alphanonce.svg';
export { default as Kenetic } from './ourPartner/kenetic.svg';
export { default as Hashkey } from './ourPartner/hashkey.svg';
export { default as FileBlocks } from './ourPartner/fileblocks.svg';
export { default as Chris } from './Chris.png';
export { default as DoubleQuotes } from './DoubleQuotes.svg';